### ISSUE TITLE
Oak's spying and meddling is actually interfering with my ability to play how I want

### ISSUE THREAD

**Issue by flarn2006** [TwitchPlaysPokemon/tppcrystal251pub#1]
We all know how Oak spies on you and is somehow able to prevent you from riding my bike indoors. That I can tolerate. I can even tolerate him getting in the way of me exercising my religious beliefs (i.e. praising Helix.) But I just got past the Nugget Bridge, and someone gave me a great offer that has the potential to change the whole game. Naturally, I accepted. But somehow, Oak heard me, and is preventing me from accepting the offer. Where's the option to say, "Fuck you, Oak, I'll do what I want!" and take the offer anyway?

**Comment by luckytyphlosion** [comment]
pls.

(please give context)

**Comment by flarn2006** [comment]
He won't let me join Team Rocket. I want to play as a villain for a change!

(Seriously though, I understand not wanting to program in a whole story arc for that, but at least give a realistic reason to not let you join. Oak wouldn't really be able to stop you.)

**Comment by Pigu-A** [comment]
You'll have to switch your religious beliefs to the Dome if you want to join Team Rocket, which we condemn. As such, this feature will not be implemented.

**Comment by flarn2006** [comment]
Figures they'd support Dome... ![DansGame](https://static-cdn.jtvnw.net/emoticons/v1/33/1.0)

**Comment by PikalaxALT** [comment]
Kappa
